POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin1"
}

###

GET http://localhost:3000/api/user/1
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjEyNzkxNjYxLCJleHAiOjE2MTI3OTE2OTF9.NCuUv4RzU2SUquAmNLky2TEPLGhh_iU5HFxjFJ442kw"
}

###

POST http://localhost:3000/api/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjEyNzkxNjYxLCJleHAiOjE2MTI3OTE3MjF9.-ulO3BTQBvJwMBu2VF7FBvpAEBxI-iyO6YLFwrTm5tU"
}