POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

GET http://localhost:3000/api/user/1
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEyNzg4Njk2LCJleHAiOjE2MTI3ODg3MjZ9.hardoT9XeLjpJS_iU7H0JzogIQ233Vw27FiiN-cmNpU"
}

###

POST http://localhost:3000/api/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEyNzg4Njk2LCJleHAiOjE2MTI3ODg3NTZ9.pUD9D47ViTyppPMT_BF2itM0-FNLO2iZ1mAIZBr_kSI"
}